name: Build README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Her gün gece yarısı çalışır

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          USER_NAME: ${{ github.repository_owner }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: python today.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update profile stats"
          git push
